# Generated by Django 4.1.2 on 2022-10-26 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_agent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_super',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
    ]
