# Generated by Django 4.1.2 on 2022-10-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sponsor',
        ),
        migrations.CreateModel(
            name='SponsoredStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.sponsor')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
